#version: "3.9"

services:
  postgres:
    image: postgres:16
    container_name: bank-postgres
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
#    ports:
#      - "5433:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

  app:
    build: .
    container_name: bank-app
    depends_on:
      - postgres
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/postgres
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 123
      JWT_SECRET: my-secret-key
      JWT_EXPIRATION: 3600000
    restart: always

volumes:
  pg_data:
