spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://postgresql:5432/postgres}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:123}

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
    properties:
      hibernate:
        format_sql: true

  liquibase:
    change-log: classpath:db/migration/db.changelog-master.yaml
    enabled: true

server:
  port: 8080

jwt:
  secret: "my-super-secret-key-my-super-secret-key-123456"
  expiration: 3600000


app:
  card:
    mask: "**** **** **** %s"

logging:
  level:
#    root: DEBUG
    org.springframework.security: DEBUG
    com.bank.bankrest: DEBUG

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    disable-swagger-default-url: true