spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://postgres:5432/postgres}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:123}

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
    properties:
      hibernate:
        format_sql: true

  liquibase:
    change-log: classpath:db/migration/db.changelog-master.yaml
    enabled: true

server:
  port: 8080

jwt:
  secret: verySecretKey123456
  expiration-ms: 3600000


app:
  card:
    mask: "**** **** **** %s"

logging:
  level:
    root: DEBUG
    com.bank.bankrest: DEBUG